### ISSUE TITLE
https://achtman-lab.github.io/maketree throws 405 error

### ISSUE THREAD

**Issue by jhc9-cdc** [genpat-it/spread#1]
In testing the referenced achtman-lab instance of grapetree, I am getting a 405 error trying to initiate a grapetree session (https://achtman-lab.github.io/maketree) and failed to load resource. Thus, when I try to load a SNP distance tsv file, it says it Cannot Connect to the backend server. It doesn't have this issue when I load the local install of the win version. What do you recommend to resolve this configuration issue?  How did you resolve it with your Grapetree Extended version?

**Comment by aldelucaizs** [comment]
Thanks for reaching out!

You are right, the original grapetree's attempt to connect to the `/maketree` backend service, which is indicated by the cannot_connect flag being set to true when the backend service is unreachable or returns a 405 error.

In the original grapetree code, `try_backend()` function is called on page load to check the connection to the backend (https://github.com/achtman-lab/GrapeTree/blob/f92fe3e04247fef9b080abcb0fe14b4b3fd0b8ab/MSTree_holder.html#L1006).

The error "Cannot Connect to the backend server" is likely triggered when the function `distributeFile()` is executed during file drag and drop (https://github.com/achtman-lab/GrapeTree/blob/f92fe3e04247fef9b080abcb0fe14b4b3fd0b8ab/static/js/tree/grapetree_fileHandler.js#L147)

In our extended version of grapetree, we don't encounter this issue because we completely bypassed any connection to their backend. This means our version does not depend on the /maketree service, eliminating the possibility of encountering this specific 405 error.

Feel free to reach out if you need further assistance or if you'd like to discuss this in more detail!

**Comment by jhc9-cdc** [comment]
Thanks for the response.  So, if you disabled this feature, how are you building the .NWK file from the initial SNP matrix? Do you have other companion  software code within Spread to accomplish this?  Is it available as part of your downloadable docker version?

Jeffrey Chrismon
Project Manager, PMP®, CSM®, Certified SAFe® Agilist
Peraton Contractor
Centers for Disease Control and Prevention
Mobile: (678) 643-3896  |  Email: ***@***.******@***.***>
DTBE Technical Support Helpdesk: ServiceDesk.cdc.gov<https://servicedesk.cdc.gov/>
***@***.***
